services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: unless-stopped
    user: ${JENKINS_USER}
    ports:
      - "${JENKINS_PORT}:8080"
      - "${JENKINS_AGENT_PORT}:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - CASC_JENKINS_CONFIG=${JENKINS_CASC_CONFIG}
      - CI_USER_PASSWORD=${JENKINS_CI_USER_PASSWORD}
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc_configs/jenkins.yml:/var/jenkins_home/casc_configs/jenkins.yml
    networks:
      - jenkins_network
    depends_on:
      dind:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl -fs http://localhost:8080/login | grep -q 'Sign in to Jenkins'" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "${JENKINS_CPU_LIMIT}"        # Limit Jenkins to 2 CPU cores
          memory: "${JENKINS_MEMORY_LIMIT}"   # Max 4GB RAM for Jenkins
        reservations:
          cpus: "${JENKINS_CPU_RESERVATION}"       # Ensure at least 1 CPU is reserved
          memory: "${JENKINS_MEMORY_RESERVATION}"  # Ensure at least 2GB RAM is reserved

  dind:
    # The Docker daemon running in docker:dind, and Jenkins' agents will send docker commands here...
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      # TODO: Fix insecure access warnings in logs
      - DOCKER_TLS_CERTDIR=${DOCKER_TLS_CERTDIR}
    volumes:
      - dind_data:/var/lib/docker
    healthcheck:
      test: ["CMD", "sh", "-c", "docker version --format '{{.Server.Version}}' || exit 1"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - jenkins_network
    deploy:
      resources:
        limits:
          cpus: "${DIND_CPU_LIMIT}"        # Limit dind to 2 CPU cores
          memory: "${DIND_MEMORY_LIMIT}"   # Max 4GB RAM for dind
        reservations:
          cpus: "${DIND_CPU_RESERVATION}"        # Ensure at least 1 CPU is reserved
          memory: "${DIND_MEMORY_RESERVATION}"   # Ensure at least 2GB RAM is reserved

volumes:
  dind_data:
  jenkins_home:

networks:
  jenkins_network:
