services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: unless-stopped
    user: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - ADMIN_PASSWORD=Admin@123
      - CI_USER_PASSWORD=cI_User@123
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yml
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc_configs/jenkins.yml:/var/jenkins_home/casc_configs/jenkins.yml
    networks:
      - jenkins_network
    depends_on:
      dind:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "sh", "-c", "curl -fs http://localhost:8080/login | grep -q 'Sign in to Jenkins'" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  dind:
    # The Docker daemon running in docker:dind, and Jenkins' agents will send docker commands here...
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      # TODO: Fix insecure access warnings in logs
      - DOCKER_TLS_CERTDIR=  # Disables TLS so it listens on 2375
    volumes:
      - dind_data:/var/lib/docker
    healthcheck:
      test: ["CMD", "sh", "-c", "docker version --format '{{.Server.Version}}' || exit 1"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - jenkins_network

volumes:
  dind_data:
  jenkins_home:

networks:
  jenkins_network:
