# For docs / examples:
# https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos
# For reference:
# http://localhost:8080/manage/configuration-as-code/reference
jenkins:
  systemMessage: "Welcome to Jenkins powered by Configuration as Code!"

  # Set the number of executors (parallel builds)
  numExecutors: 0
