jenkins:
  # Security settings (disable first-run setup wizard)
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Administrator"
          password: "${decodeBase64:${readFile:/var/jenkins_home/secrets/admin_password}}"
        - id: "ci_user"
          name: "CI_User"
          password: "${decodeBase64:${readFile:/var/jenkins_home/secrets/ci_user_password}}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy:
      manuallyProvidedKeyVerificationStrategy:
        approvedHostKeys: |-
          # Get the GitLab's key by running: ssh-keyscan -t ed25519 gitlab.com
          gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf