# For docs / examples:
# https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos
jenkins:
  systemMessage: "Welcome to Jenkins powered by Configuration as Code!"

  # Set the number of executors (parallel builds)
  numExecutors: 0

  # Set global environment variables
  globalNodeProperties:
    - envVars:
        env:
          - key: TEST_VARIABLE
            value: "Hello World"

  # Security settings (disable first-run setup wizard)
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Administrator"
          password: "${ADMIN_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  nodes:
    - permanent:
        name: "jenkins-agent-1"
        remoteFS: "/home/jenkins"
        numExecutors: 2
        mode: NORMAL
        labelString: "docker"
        launcher:
          ssh:
            host: "jenkins-jenkins_agent-1"
            port: 22
            credentialsId: "jenkins-agent-ssh"
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false

    - permanent:
        name: "jenkins-agent-2"
        remoteFS: "/home/jenkins"
        numExecutors: 2
        mode: NORMAL
        labelString: "docker"
        launcher:
          ssh:
            host: "jenkins-jenkins_agent-2"
            port: 22
            credentialsId: "jenkins-agent-ssh"
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false

unclassified:
  timestamper:
    allPipelines: true
    systemTimeFormat: "yyyy-MM-dd HH:mm:ss.SSS"
  location:
    url: "http://localhost:8080/"
  mailer:
    smtpHost: "smtp.example.com"

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              id: "jenkins-agent-ssh"
              description: "SSH key for Jenkins agents"
              scope: GLOBAL
              username: "jenkins"
              privateKeySource:
                directEntry:
                  privateKey: "${readFile:${SSH_PRIVATE_KEY_PATH}}"

# Configure pipeline jobs via Job DSL plugin
jobs:
  - script: |
      pipelineJob('Print Docker Version') {
        definition {
          cps {
            script("""
              pipeline {
                agent any
                stages {
                  stage('Print Docker Version') {
                    steps {
                      sh 'docker version'
                    }
                  }
                }
              }
            """.stripIndent())
            sandbox()
          }
        }
      }

      pipelineJob('Print Docker Info') {
        definition {
          cps {
            script("""
              pipeline {
                agent any
                stages {
                  stage('Print Docker Info') {
                    steps {
                      sh 'docker info'
                    }
                  }
                }
              }
            """.stripIndent())
            sandbox()
          }
        }
      }
