# For docs / examples:
# https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos
# For reference:
# http://localhost:8080/manage/configuration-as-code/reference
jenkins:
  systemMessage: "Welcome to Jenkins powered by Configuration as Code!"

  # Set the number of executors (parallel builds)
  numExecutors: 0

  # Set global environment variables
  globalNodeProperties:
    - envVars:
        env:
          - key: TEST_VARIABLE
            value: "Hello World"

  # Security settings (disable first-run setup wizard)
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Administrator"
          password: "${ADMIN_PASSWORD}"
        - id: "ci_user"
          name: "CI_User"
          password: "${CI_USER_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - x509ClientCert:
              scope: SYSTEM
              id: "docker_tls_certificate"
              # TODO: Note: these will be visible in http://localhost:8080/manage/configuration-as-code/viewExport
              # Is that fine? Think about it.
              clientKeySecret: "${readFile:${DOCKER_CERT_PATH}/key.pem}"
              clientCertificate: "${readFile:${DOCKER_CERT_PATH}/cert.pem}"
              serverCaCertificate: "${readFile:${DOCKER_CERT_PATH}/ca.pem}"

unclassified:
  timestamper:
    allPipelines: true
    systemTimeFormat: "yyyy-MM-dd HH:mm:ss.SSS"
  location:
    url: "http://localhost:8080/"
  mailer:
    smtpHost: "smtp.example.com"
