jobs:
  - script: >
      pipelineJob("metadata-and-seed-job-generator") {
        description("Generates metadata and seeds Jenkins jobs based on Ansible playbooks from SymbioDeployHub")
        environmentVariables {
          env('JENKINS_AGENT_SHARED_METADATA_DIR', "${JENKINS_AGENT_SHARED_METADATA_DIR}")
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  credentials("jenkins-rsa-key")
                  url("https://gitlab.com/mnf-group/tiab/octane-sys-eng/symbiodeployhub.git")
                }
                branches("stable")
              }
            }
            scriptPath("jenkins/metadata-and-seed-job-generator/Jenkinsfile")
          }
        }
      }
