name: CI/CD Workflow

on:
  push:
    branches:
      - master

env:
  DOCKER_VERSION: 5:28.0.1-1~ubuntu.24.04~noble
  DOCKER_COMPOSE_FILE: docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker with specific version
        run: sh ./install_docker.sh
        working-directory: ./.github/workflows/scripts

      - name: Check if docker compose is available before proceeding
        run: docker compose version || { echo "docker compose is not installed or not in PATH"; exit 1; }

      - name: Start and setup the container
        id: docker-start
        run: docker compose up --scale jenkins_agent=2 -d
        working-directory: ./docker/jenkins

      - name: Test Jenkins server is up and running
        run: sh tests/test_jenkins.sh
        working-directory: ./docker/jenkins

      - name: Create secrets file
        run: |
          mkdir -p secrets
          echo "cI_User@123" > secrets/ci_user_password.txt
        working-directory: ./docker/jenkins

      - name: Generate the API token for the CI_User needed to be used with test scripts
        run: sh scripts/generate_token.sh
        working-directory: ./docker/jenkins

      - name: Test Jenkins agents are online and connected
        run: sh tests/test_agents.sh
        working-directory: ./docker/jenkins

      - name: Run the sanity check pipeline
        run: sh tests/test_jobs.sh
        working-directory: ./docker/jenkins

      - name: Debug Running Containers
        if: ${{ always() }}
        run: docker ps -a

      - name: Collect Docker container logs
        if: ${{ always() }}
        run: |
          for container in $(docker ps -a --format '{{.Names}}'); do
            echo "---- Logs for $container ----"
            docker logs "$container" | sed "s/^/[$container] /"
            echo "---- End of logs for $container ----"
          done

      - name: Clean up Docker containers and volumes
        if: ${{ always() }}
        run: |
          [ -f "${{ env.DOCKER_COMPOSE_FILE }}" ] || { echo "Compose file not found!"; exit 1; }
          if docker compose ps -q | grep -q .; then
            docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} down --volumes --remove-orphans
          else
            echo "No containers to clean up."
          fi
        working-directory: ./docker/jenkins
